### ISSUE TITLE
parameter naming for selectInterval in the documentation

### ISSUE THREAD

**Issue by munaja** [frehaiku/DatePicker#6]
Hi @frehaiku 

First of all, thanks for the great library, it helps me alot in my project. 

Here i just want to point out in the documentation (main page the repository), there is parameter named selectInterval to put the range of the years. But I can't use it in the instantiation. After I check the code, calendar.js at line 28, it uses `config.interval` or default value `[1970, 2030]`. Therefore if I use `interval` instead of `selectInterval` it works. 

So I think there is some typo in the documentation. The one stated in documentation (selectInterval) is internal variable name, not the one used in the parameter (config).

Thanks

**Comment by frehaiku** [comment]
Thanks your feedback, now the documentation is updated
